# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Nazar Ivanenko
tagline:             'Notes'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://nivanenko.github.io/
shorturl:            nivanenko.github.io
paginate:            10
highlighter:         pygments

# About/contact
author:
  name:              Nazar
  email:             nazar.ivanenko@gmail.com

## Custom vars
version:             1.0.0
github:
  repo:              github.com/nivanenko/nivanenko.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  О блоге: '/about'
  Архив записей: '/archive'
  Лента: '/atom.xml'
