# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Nazar Ivanenko
tagline:             'Notes'
description:         'My personal blog for notes about programming.'
url:                 http://nivanenko.github.io/
shorturl:            nivanenko.github.io
paginate:            10
highlighter:         pygments

# About/contact
author:
  name:              Nazar
  email:             nazar.ivanenko@gmail.com

## Custom vars
github:
  repo:              http://github.com/nivanenko/nivanenko.github.io
